// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPageMonitor.Infrastructure.Data;

#nullable disable

namespace WebPageMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250515161955_CleanupDatabase2")]
    partial class CleanupDatabase2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebPageMonitor.Core.Entities.ChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiffContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageVersionId")
                        .HasColumnType("int");

                    b.Property<int>("SiteType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PageVersionId");

                    b.ToTable("ChangeLogs");
                });

            modelBuilder.Entity("WebPageMonitor.Core.Entities.PageVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("WatchedPageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WatchedPageId");

                    b.ToTable("PageVersions");
                });

            modelBuilder.Entity("WebPageMonitor.Core.Entities.WatchedPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("CheckInterval")
                        .HasColumnType("time");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WatchedPages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckInterval = new TimeSpan(0, 0, 0, 0, 0),
                            LastChecked = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            Url = "https://pass.rw.by/ru/route/?path=ru%2Froute%2F&from=%D0%93%D1%80%D0%BE%D0%B4%D0%BD%D0%BE&from_exp=&from_esr=&to=%D0%9C%D0%B8%D0%BD%D1%81%D0%BA&to_exp=2100000&to_esr=140210&front_date=%D0%BD%D0%B0+%D0%B2%D1%81%D0%B5+%D0%B4%D0%BD%D0%B8&date=everyday"
                        },
                        new
                        {
                            Id = 2,
                            CheckInterval = new TimeSpan(0, 0, 0, 0, 0),
                            LastChecked = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Url = "https://www.gismeteo.by/weather-grodno-4243/tomorrow/"
                        });
                });

            modelBuilder.Entity("WebPageMonitor.Core.Entities.ChangeLog", b =>
                {
                    b.HasOne("WebPageMonitor.Core.Entities.PageVersion", "PageVersion")
                        .WithMany()
                        .HasForeignKey("PageVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageVersion");
                });

            modelBuilder.Entity("WebPageMonitor.Core.Entities.PageVersion", b =>
                {
                    b.HasOne("WebPageMonitor.Core.Entities.WatchedPage", "WatchedPage")
                        .WithMany("Versions")
                        .HasForeignKey("WatchedPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WatchedPage");
                });

            modelBuilder.Entity("WebPageMonitor.Core.Entities.WatchedPage", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
